server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${AUTH_URI:http://auth-service:8083}
          predicates: [ Path=/api/auth/** ]
        - id: users
          uri: ${USER_URI:http://user-service:8081}
          predicates: [ Path=/api/users/** ]
        - id: devices
          uri: ${DEVICE_URI:http://device-service:8082}
          predicates: [ Path=/api/devices/** ]
        - id: monitoring-service
          uri: ${MONITORING_URI:http://monitoring-service:8084} # Assuming a Load Balancer or service name
          predicates:
            - Path=/api/monitoring/**


jwt:
  secret: ${JWT_SECRET:change-me}